version: "3"
services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  ui:
    build: .
    command: npm run watch
    volumes:
      - "./:/app"
      - "/app/node_modules"
      - "./.env:/app/.env"
    ports: 
      - "3000:3000"
    environment:
      NODE_ENV: dev
      DATABASE: mongodb://root:example@mongo:27017


